### ISSUE TITLE
Recording playback buffering problems

### ISSUE THREAD

**Issue by truncrel2** [kodi-pvr/pvr.hts#364]
I opened a thread at [LE forum](https://forum.libreelec.tv/thread/12280-tvh-some-recordings-start-with-audio-dropouts-and-buffering/). At that time I thought it was a more general problem with LE, but it turns out to be a problem that only occurs within TVH client.

**Problem description:** If I want to playback certain HD recordings (15 mbit/s average) via TVH client they start buffering after a few seconds (sometimes stuttering before) and then playback a few seconds and then slow to a crawl and audio drops out completely and playback never recovers.

**Setup where the problem occurs:**
- TVH Server V4.2.6 (Ubuntu)
- RPi2/C2 client (both tested, both identical behavior)
- LE9 development builds (from test.libreelec.tv and Milhouse on RPi2)
- TVH Client V4.2.13.2 and V4.2.14 (latter only tested on RPi2)

**Observations/contraindication:**
- this does not happen on LE 8.2 with TVH client version 3.4.27.1
- bandwidth server->client is sufficient (iperf3: 90mbit/s+ throughput)
- same recordings on LE9 playback fine via smb
- memory usage when I start recordings via TVH client is very low at start when compared to SMB and only gets higher after first buffering, which takes about 12 seconds
- the problem even happens on SD/MPEG-2 recordings but rarely and it keeps running after the buffering
- playback of HD LiveTV does not seem to be affected (even time shifted)

**Comment by ksooo** [comment]
Nothing related has changed in pvr.hts for ages - so, I would say the cause for this problems are changes in Kodi Leia itself.

**Comment by truncrel2** [comment]
Ok, so I "methodically" tested (divide and conquer) Milhouse' versions and found the offending version which is 2017-09-12. The version a day before is working as expected. 

Pls keep in mind that "New" at the top is accumulative and therefore mostly the same as in 2017-09-11. Build details seem to contain the most interesting parts.
[2017-09-12 changelog](https://forum.kodi.tv/showthread.php?tid=298461&pid=2646059#pid2646059)

**Comment by gb160** [comment]
Im seeing exactly the same behaviour using the Leia Alpha on MacOS.
That has v4.2.13
On my iPad using an older nightly of Leia which has v4.2.12 and that is working perfectly.
I can confirm its just on playback of recordings, live TV is working fine.

**Comment by gb160** [comment]
Actually discard the above, the problem is still present..i checked it with a different recording which had a lower bitrate and it played ok.
When i tested it with the same recording that was stuttering on MacOS it buffered as well.

I tried the openElec version that @truncrel2 mentioned was the last working version and can confirm the same findings...only problem is i cant get Netflix working on that version :(

It does seem to be a Leia problem rather than a pvr.hts problem so god knows when this is likely to be resolved.

**Comment by truncrel2** [comment]
It's actually hard to tell. I pinpointed the PR that triggers this issue, however this PR* is pretty unrelated. Also it seems that there is no intention of fixing this issue.

*PR: https://github.com/xbmc/xbmc/pull/12474/commits

**Comment by Jalle19** [comment]
Are you sure it's that PR?

**Comment by gb160** [comment]
Something else strange...the problem completely disappears with a hardwired network.
Strange because on wifi i was still getting 50-60mbit/s through iperf, so i dont know why this is an issue.

Switch to ethernet and its perfect again.
Definitely something changed in Leia because with 17.6 it works perfectly on exactly the same setup on wifi.

I'll have to stick to ethernet until this gets resolved, if it ever does.

**Comment by Jalle19** [comment]
People have reported similar issues on wifi since forever, are you sure your issue goes away with 17.6?

**Comment by gb160** [comment]
@Jalle19 Yep ive just confirmed on MacOS

Krypton 17.6 Works perfectly on Wifi, the buffer fills immediately to 100% and never drops below 98%.

Leia Alpha, the buffer starts decreasing as soon as playback starts, once its hits zero the stuttering starts and it never recovers.

Both only tested using Wifi.

It wouldnt be hard to find the version that introduced the issue, but the old nightlies aren't available on MacOS...the only device where the old versions are still available that i have a device for is a Pi, and i confirmed this by installing the version that @truncrel2 mentioned in this thread.

As mentioned using wired ethernet solves it for me on Leia, if it wasn't for Netflix id have just stuck with 17.6

**Comment by ksooo** [comment]
https://github.com/xbmc/xbmc/pull/14002 :-)

**Comment by gb160** [comment]
@ksooo forgive my ignorance here, but does that signify you've solved the issue?
Excellent work if so.

Any idea when this is likely to make the nightlies?

**Comment by ksooo** [comment]
Should be fixed with https://github.com/kodi-pvr/pvr.hts/pull/366

**Comment by gb160** [comment]
Excellent, just built it and tested it, clears up all issues for me...buffering completely gone on wifi.

**Comment by truncrel2** [comment]
Just tested Milhouse build from 10th of June (probable fix was incorporated on 9th) and voila it works. Thank you @ksooo for fixing the bug. I still don't know why this was triggered by a seemingly unrelated PR, but I only care a little, because it is far too complex for me :D 

PS.: @Jalle19 I described my approach in the LE forum thread that I linked in OP. I basically reverted the kodi code base to the last working PR/day and cherry-picked only the mentioned PR. It might be the PR itself somehow triggering the bug or it has something to do with the renaming I had to do in order to get to compile (that was in line with further refactoring in the kodi tree). That is hard to guess for me.

**Comment by trimethia** [comment]
@ksooo  @truncrel2 
I am still observing very slow buffering with LibreElec 8.95.002 (on an odroid C2) when playing a recording from the TVH server (on an odroid XU4 wunning Ubuntu 18) via Internet. Streaming works perfectly. 

I have noticed that increasing the reading chunk size from 64 to 128 KB does seem to help, but buffering still occurs. Is there any rationale with using 128KB as the maximum value? Would it be possible to double it? Thanks.

https://github.com/kodi-pvr/pvr.hts/pull/366/files#diff-f795af7261ba65d71ad31c6d1b795390R23

**Comment by Jalle19** [comment]
@trimethia can you change the settings XML manually to allow for larger values and see if it has any impact?

**Comment by trimethia** [comment]
@digiaonline Thanks, didn't know that it was possible to change the settings file without rebuilding. Just confirmed that setting a value of 256 solves all my buffering issues.

**Comment by trimethia** [comment]
@jalle19 Thanks, didn't know that it was possible to change the settings file without rebuilding. Just confirmed that setting a value of 256 solves all my buffering issues.

**Comment by bernhardberger** [comment]
Sorry to re-open this, but that problem isn't TVH exclusive.

Same behaviour when playing back recordings from DVBViewer (at least since Leia Beta). Was hoping it would get fixed, but hasn't changed to date.

pvr:// stuff buffers and then crops out tge exact same way the opening post describes.

Recordings are played perfectly fine when opened directly in Kodi via Samba share.

- DVBViewer Media Server on Win10 Server
- Kodi on nVidia Shield
- Kodi Leia

**Comment by ksooo** [comment]
This is the tvh addon repo. If you experience problems with the dvbviewer addon, open an issue in the respective repo, please.

**Comment by jobrien2001** [comment]
I too fixed my buffering problems by adjusting the chunk size. 256 was better but not enough for me, smooth playback was achieved with 384.

Would be good to include a note somewhere in the addon.
