### ISSUE TITLE
Programme summary missing in Kodi EPG (pvr.hts 4.4.10)

### ISSUE THREAD

**Issue by biryets** [kodi-pvr/pvr.hts#395]
In the latest pvr.hts Kodi addon (4.4.10) , the programme summary is missing from the Kodi EPG. The programme title and subtitles are however shown ok 
The summary is shown ok in 4.4.6.

**Comment by ksooo** [comment]
This is definitely not a pvr.hts problem.

**Comment by gapone** [comment]
I have the same issue. All the epg info is ok in the tvheadend gui. If epg is on the same line then you have a problem and it's not happening with all channels. See my thread on kodi pvr forum.

https://forum.kodi.tv/showthread.php?tid=339485

**Comment by biryets** [comment]
EPG  works fine with 4.4.6. The summary disapears when I update addon to 4.4.10. This was repeatable on Windows 10, OSMC and Coreelec systems. No other changes made.

**Comment by gapone** [comment]
Same here and summary is there in the channel list but it is cut out as you can see from my pictures. If the summary is cut out, then you get no information available when changing a channel.

**Comment by ksooo** [comment]
There are no changes between pvr.hts 4.4.6 and 4.4.10 that may have introduced this change in behavior.

**Comment by biryets** [comment]
It seems like this issue has fallen on No man's land. 
The loss of the summary has happened after the add-on update and the issue can be replicated.
It is affecting Android, Linux and Windows clients. 

@ksooo as someone with knowledge of all 3, can you please investigate and advise where to turn to?

Kodi team response: “i can't think of a reason how a skin can be responsible...”
https://forum.kodi.tv/showthread.php?tid=339485&pid=2810925#pid2810925
TVheadend response: “Yes, report this here: https://github.com/kodi-pvr/pvr.hts/issues”
https://tvheadend.org/issues/5501#note-2
PVR.hts response: “This is definitely not a pvr.hts problem.”

**Comment by ksooo** [comment]
Maybe it actually is a pvr.hts problem caused by increasing the htsp client version in 4.4.8

**Comment by ksooo** [comment]
@biryets the real issue is that your epg meta data do only contain a "summary" (plot outline), but no "description" (plot). In this case, older tvh versions copied the summary (plot outline) to description (plot). This fallback was removed in tvh with htsp version 32 and pvr.hts gets no description (summary) any more. The fix is to now have the fallback logics in pvr.hts.

**Comment by gapone** [comment]
How long does it take to update to android addons repository? I will test this asap and thanks for the fix...

**Comment by ksooo** [comment]
> I have the same issue. All the epg info is ok in the tvheadend gui. If epg is on the same line then you have a problem and it's not happening with all channels. 

 If you see the summary in channels window but not in epg window, then you don't have the same problem as @biryets  (and my fix will most probably not fix what you describe).

**Comment by gapone** [comment]
> > I have the same issue. All the epg info is ok in the tvheadend gui. If epg is on the same line then you have a problem and it's not happening with all channels.
> 
> If you see the summary in channels window but not in epg window, then you don't have the same problem as @biryets (and my fix will most probably not fix what you describe).

I'm pretty sure that I have the same problem because I installed 4.4.6 and everything is fixed. I have also description plot missing on some channels and 4.4.6 fixed it. Just have to wait 4.4.12 for android...

**Comment by Verequies** [comment]
This is still an issue. Running 4.4.12/master, and TVHeadend 4.3-1733~g7d3aa1194, a bunch of channels do not show the description. Changing the built-in HTPS version back down to 31 solves the problem.

**Comment by ksooo** [comment]
If you are able to build you are by any chance able to debug this...

**Comment by Verequies** [comment]
I have submitted a pull request to fix this issue. #401

**Comment by ksooo** [comment]
👍

**Comment by biryets** [comment]
All seems to be working well now. Thanks
